src/Entity/Blog.php
<?php

namespace App\Entity;

use App\Repository\BlogRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Symfony\Component\HttpFoundation\File\File;

/**
 * @ORM\Entity(repositoryClass=BlogRepository::class)
 * @Vich\Uploadable
 */
class Blog
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $Title;

    /**
     * @ORM\Column(type="text")
     */
    private $Description;

    /**
     * @ORM\Column(type="datetime")
     */
    private $Date;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="blogs")
     */
    private $parent;

    /**
     * @ORM\OneToMany(targetEntity=Images::class, mappedBy="blog")
     */
    private $images;

    /**
     * @ORM\OneToMany(targetEntity=CommentsBlog::class, mappedBy="blog", cascade={"persist"}, orphanRemoval=true)
     */
    private $commentsBlogs;

    /**
     * @ORM\Column(type="string", length=255)
     * @var string
     */
    private $image;

    /**
     * @Vich\UploadableField(mapping="vue_images", fileNameProperty="image")
     * @var File
     */
    private $imageFile;

    public function __construct()
    {
        $this->images = new ArrayCollection();
        $this->commentsBlogs = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->Title;
    }

    public function setTitle(string $Title): self
    {
        $this->Title = $Title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(string $Description): self
    {
        $this->Description = $Description;

        return $this;
    }

    public function getDate(): ?\DateTime
    {
        return $this->Date;
    }

    public function setDate(\DateTime $Date): self
    {
        $this->Date = $Date;

        return $this;
    }

    public function getParent(): ?User
    {
        return $this->parent;
    }

    public function setParent(?User $parent): self
    {
        $this->parent = $parent;

        return $this;
    }

    /**
     * @return Collection<int, Images>
     */
    public function getImages(): Collection
    {
        return $this->images;
    }

    public function addImage(Images $image): self
    {
        if (!$this->images->contains($image)) {
            $this->images[] = $image;
            $image->setBlog($this);
        }

        return $this;
    }

    public function removeImage(Images $image): self
    {
        if ($this->images->removeElement($image)) {
            // set the owning side to null (unless already changed)
            if ($image->getBlog() === $this) {
                $image->setBlog(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, CommentsBlog>
     */
    public function getCommentsBlogs(): Collection
    {
        return $this->commentsBlogs;
    }

    public function addCommentsBlog(CommentsBlog $commentsBlog): self
    {
        if (!$this->commentsBlogs->contains($commentsBlog)) {
            $this->commentsBlogs[] = $commentsBlog;
            $commentsBlog->setBlog($this);
        }

        return $this;
    }

    public function removeCommentsBlog(CommentsBlog $commentsBlog): self
    {
        if ($this->commentsBlogs->removeElement($commentsBlog)) {
            // set the owning side to null (unless already changed)
            if ($commentsBlog->getBlog() === $this) {
                $commentsBlog->setBlog(null);
            }
        }

        return $this;
    }
    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(string $image): self
    {
        $this->image = $image;

        return $this;
    }
    public function setImageFile(File $image = null)
    {
        $this->imageFile = $image;

        // VERY IMPORTANT:
        // It is required that at least one field changes if you are using Doctrine,
        // otherwise the event listeners won't be called and the file is lost
        if ($image) {
            // if 'updatedAt' is not defined in your entity, use another property
            $this->updatedAt = new \DateTime('now');
        }
    }

    public function getImageFile()
    {
        return $this->imageFile;
    }

    public function _toString()
    {
        return $this->Title;
    }
}

src/Entity/Contact.php
<?php

namespace App\Entity;

use App\Repository\ContactRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ContactRepository::class)
 */
class Contact
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $prenom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $numero;

    /**
     * @ORM\Column(type="text")
     */
    private $message;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date;

    /**
     * @ORM\Column(type="boolean")
     */
    private $Etat;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getNumero(): ?string
    {
        return $this->numero;
    }

    public function setNumero(?string $numero): self
    {
        $this->numero = $numero;

        return $this;
    }

    public function getMessage(): ?string
    {
        return $this->message;
    }

    public function setMessage(string $message): self
    {
        $this->message = $message;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function isEtat(): ?bool
    {
        return $this->Etat;
    }

    public function setEtat(bool $Etat): self
    {
        $this->Etat = $Etat;

        return $this;
    }
}

src/Entity/Reviews.php
<?php

namespace App\Entity;

use App\Repository\ReviewsRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ReviewsRepository::class)
 */
class Reviews
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $firstname;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $lastname;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Note;

    /**
     * @ORM\Column(type="text")
     */
    private $Avis;

    /**
     * @ORM\Column(type="boolean")
     */
    private $Etat;

    /**
     * @ORM\ManyToOne(targetEntity=Formations::class, inversedBy="reviews")
     */
    private $parent;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): self
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(string $lastname): self
    {
        $this->lastname = $lastname;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getNote(): ?string
    {
        return $this->Note;
    }

    public function setNote(string $Note): self
    {
        $this->Note = $Note;

        return $this;
    }

    public function getAvis(): ?string
    {
        return $this->Avis;
    }

    public function setAvis(string $Avis): self
    {
        $this->Avis = $Avis;

        return $this;
    }

    public function isEtat(): ?bool
    {
        return $this->Etat;
    }

    public function setEtat(bool $Etat): self
    {
        $this->Etat = $Etat;

        return $this;
    }

    public function getParent(): ?Formations
    {
        return $this->parent;
    }

    public function setParent(?Formations $parent): self
    {
        $this->parent = $parent;

        return $this;
    }

    public function getDate(): ?\DateTime
    {
        return $this->date;
    }

    public function setDate(\DateTime $date): self
    {
        $this->date = $date;

        return $this;
    }
}

src/Controller/ViewBlogController.php
<?php

namespace App\Controller;

use App\Entity\CommentsBlog;
use App\Form\CommentsBlogType;
use App\Repository\BlogRepository;
use App\Repository\CommentsBlogRepository;
use App\Repository\FormationsRepository;
use Symfony\Component\HttpFoundation\Request;
use App\Repository\UserRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * Class ViewBlogController
 * @package App\Controller
 * @Route("/blogs", name="blogs_")
 */


class ViewBlogController extends AbstractController
{
    /**
     * @Route("/{id}", name="app_view_blog")
     */
                public function index(int $id,
                                      BlogRepository $blogRepository,
                                      CommentsBlogRepository $commentsBlogRepository,
                                      FormationsRepository $formationsRepository,
                                      Request $request
                ): Response
    {
        #POUR OUVRIR LE BLOG SUR LA PAGE AVEC L'ID #
        $blogs= $blogRepository->find($id);

        #POUR FORMULAIRE DE COMMENTAIRES#
        $blogComment = new CommentsBlog();
        $form = $this->createForm(CommentsBlogType::class, $blogComment);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->getDoctrine()->getManager();

            #ON SET DATE D'AUJOURD'HUI ET L'ETAT A 0#
            $blogComment->setDate(new \DateTime('now'));
            $blogComment->setEtat("0");

            #ON S'EN SERT POUR QUE LE COMMENTAIRE OBTIEN L'ID DU BLOG#
            $id = $blogRepository->find($id);
            $blogComment->setBlog($id);

            $em->persist($blogComment);
            $em->flush();
        }
        return $this->render('view_blog/index.html.twig', [
            "blogs"=>$blogs,
            'allBlogs'=> $blogRepository -> findAll(),
            'comments' => $commentsBlogRepository ->findAll(),
            'other' => $blogRepository ->findAll(),
            'formations'=> $formationsRepository ->findAll(),
            'commentBlog' => $form->createView()
        ]);
    }
}

templates/view_blog/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ blogs.title|upper }}{% endblock %}

{% block body %}
    <link rel="stylesheet" type="text/css" href="{{ asset("assets/vendor/font-awesome/css/all.min.css") }}">
    <link rel="stylesheet" type="text/css" href="{{ asset("assets/vendor/bootstrap-icons/bootstrap-icons.css") }}">
    <link rel="stylesheet" type="text/css" href="{{ asset("assets/vendor/tiny-slider/tiny-slider.css") }}">
    <link rel="stylesheet" type="text/css" href="{{ asset("assets/vendor/glightbox/css/glightbox.css") }}">
    <link id="style-switch" rel="stylesheet" type="text/css" href="{{ asset("assets/css/style.css") }}">

    <!-- =======================
Main Content START -->
    <main>
        <section class="pb-0 pt-5 pb-md-5">
            <div class="container">
                <div class="row g-0 g-lg-5">
                    <div class="col-xl-8">
                        <!-- Pre title -->
                        <span>{{ blogs.date|date('d-m-Y') }}</span>
                        <span class="mx-2">|</span>
                        <div class="badge bg-orange text-white">Blog</div>
                        <!-- Title -->
                        <h2>{{ blogs.title|upper }}</h2>
                        <!-- Info -->
                        <p> {{ blogs.description|raw }}</p>
                    </div>

                    <!-- Left sidebar START -->
                    <div class="col-lg-4">
                        <div class="row">
                            <div class="col-md-6 col-lg-12">
                                <!-- Instructor image START -->
                                <div class="card shadow p-2 mb-4 text-center">
                                    <!-- Card body -->
                                    <div class="card-body px-3">
                                        <!-- Rating -->
                                        <h5>Partagez sur: </h5>
                                        <!-- Social media button -->
                                        <ul class="list-inline mb-0">
                                            <li class="list-inline-item"><a class="btn px-2 btn-sm bg-facebook"  href="#">
                                                <i class="fab fa-fw fa-facebook-f"></i></a></li>
                                            <li class="list-inline-item"><a class="btn px-2 btn-sm bg-instagram-gradient" href="#">
                                                <i class="fab fa-fw fa-instagram"></i></a></li>
                                            <li class="list-inline-item"><a class="btn px-2 btn-sm bg-twitter" href="#">
                                                <i class="fab fa-fw fa-twitter"></i></a></li>
                                            <li class="list-inline-item"><a class="btn px-2 btn-sm bg-linkedin" href="#">
                                                <i class="fab fa-fw fa-linkedin-in"></i></a></li>
                                        </ul>
                                    </div>
                                </div>
                                <!-- Instructor image END -->
                            </div>

                            <div class="col-md-6 col-lg-12">
                                <div class="card card-body shadow p-4 mb-4">

                                    <!-- Education START -->
                                    <!-- Title -->
                                    <h4 class="mb-3">Formations</h4>

                                    {% for formations in formations %}
                                    <div style="margin-left: 15px;">
                                        <a href="{{ path('formation_app_view_formations',{'id':formations.id}) }}" style="color:#747579;">
                                            <h7> {{ formations.title|upper }}</h7>
                                        </a>
                                    </div>
                                    {% endfor %}
                                </div>
                            </div>
                        </div> <!-- Row End -->
                    </div>
                    <!-- Left sidebar END -->

                    <div class="col-12">

                        <hr> <!-- Divider -->

                        <!-- Comment review and form START -->
                        <div class="row mt-4">
                            <!-- Comment START -->
                            <div class="col-md-7">
                                <h3>Commentaires</h3>

                                <!-- Comment level 1-->
                                {% for comments in blogs.commentsBlogs %}
                                    {% if comments.etat == 1 %}
                                        <div class="my-4 d-flex">
                                            <div>
                                                <div class="mb-2">
                                                    <h5 class="m-0">{{ comments.prenom|lower }} {{ comments.nom|upper }}</h5>
                                                    <span class="me-3 small">{{ comments.date|date('d-m-Y') }}</span>
                                                </div>
                                                <p>{{ comments.avis }}</p>
                                            </div>
                                        </div>
                                    {% endif %}
                                {% endfor %}
                            </div>
                            <!-- Comment END -->

                            <!-- Form START -->
                            <div class="col-md-5">
                                <!-- Title -->
                                <h3 class="mt-3 mt-sm-0">Votre avis nous interesse!</h3>
                                <small>Votre email oires</small>

                                {{ form_start(commentBlog, {'attr': {'class': 'row g-3 mt-2 mb-5'}}) }}
                                <!-- Name -->
                                <div class="col-lg-6">
                                    <label class="form-label">Nom *</label>
                                    {{ form_row(commentBlog.nom, {'attr': {'class': 'form-control'}}) }}
                                </div>
                                <!-- Prenom -->
                                <div class="col-lg-6">
                                    <label class="form-label">Prenom *</label>
                                    {{ form_row(commentBlog.prenom, {'attr': {'class': 'form-control'}}) }}
                                </div>
                                <!-- Email -->
                                <div class="col-lg-20">
                                    <label class="form-label">Email *</label>
                                    {{ form_row(commentBlog.email, {'attr': {'class': 'form-control'}}) }}
                                </div>
                                <!-- Comment -->
                                <div class="col-12">
                                    <label class="form-label">Avis *</label>
                                    {{ form_row(commentBlog.avis, {'attr': {'class': 'form-control'}}) }}
                                </div>
                                <!-- Button -->
                                <div class="col-12">
                                    <button type="submit" class="btn btn-primary mb-0">Publier</button>
                                </div>
                                {{ form_end(commentBlog) }}

                            </div>
                            <!-- Form END -->
                        </div>
                        <!-- Comment review and form END -->
                    </div>
                </div> <!-- Row END -->
            </div>
        </section>
        <!-- =======================
        Main Content END -->

        <!-- =======================
        Related blog START -->
        <section class="pt-0">
            <div class="container">
                <!-- Title -->
                <div class="row mb-4">
                    <div class="col-12">

                        <h2 class="mb-0">Vous pouvez aimer aussi</h2>
                    </div>
                </div>

                <!-- Slider START -->
                <div class="tiny-slider arrow-round arrow-hover arrow-dark">


                    <div class="tiny-slider-inner" data-autoplay="false" data-arrow="true" data-edge="2"
                         data-dots="false" data-items="3" data-items-lg="2" data-items-sm="1">
                        <!-- Slider item -->
                        {% for allBlogs in allBlogs %}
                            <div class="card bg-transparent">
                                <div class="row g-0">
                                    <!-- Image -->
                                    <div class="col-md-4">
                                        <img src="{{ vich_uploader_asset(allBlogs, 'imageFile') }}"
                                             class="img-fluid rounded-start" alt="...">
                                    </div>
                                    <!-- Card body -->
                                    <div class="col-md-8">
                                        <div class="card-body">
                                            <!-- Title -->
                                            <h6 class="card-title">
                                                <a href="{{ path('blogs_app_view_blog',{'id':allBlogs.id}) }}">{{ allBlogs.title|u.truncate(45, '...', false) }}</a>
                                            </h6>
                                            <span class="small">{{ allBlogs.date|date('d-m-Y') }}</span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                </div>
                <!-- Slider END -->
            </div>
        </section>
    </main>
    <!-- **************** MAIN CONTENT END **************** -->


{% endblock %}