src/Entity/Actualites.php
<?php

namespace App\Entity;

use App\Repository\ActualitesRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ActualitesRepository::class)
 */
class Actualites
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $Title;

    /**
     * @ORM\Column(type="text")
     */
    private $Description;

    /**
     * @ORM\Column(type="datetime")
     */
    private $Date;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="actualites")
     */
    private $parent;

    /**
     * @ORM\OneToMany(targetEntity=Images::class, mappedBy="actualites")
     */
    private $images;

    /**
     * @ORM\OneToMany(targetEntity=CommentsActu::class, mappedBy="actu", cascade={"persist"}, orphanRemoval=true)
     */
    private $commentsActus;

    public function __construct()
    {
        $this->images = new ArrayCollection();
        $this->commentsActus = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->Title;
    }

    public function setTitle(string $Title): self
    {
        $this->Title = $Title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(string $Description): self
    {
        $this->Description = $Description;

        return $this;
    }

    public function getDate(): ?\DateTime
    {
        return $this->Date;
    }

    public function setDate(\DateTime $Date): self
    {
        $this->Date = $Date;

        return $this;
    }

    public function getParent(): ?User
    {
        return $this->parent;
    }

    public function setParent(?User $parent): self
    {
        $this->parent = $parent;

        return $this;
    }

    /**
     * @return Collection<int, Images>
     */
    public function getImages(): Collection
    {
        return $this->images;
    }

    public function addImage(Images $image): self
    {
        if (!$this->images->contains($image)) {
            $this->images[] = $image;
            $image->setActualites($this);
        }

        return $this;
    }

    public function removeImage(Images $image): self
    {
        if ($this->images->removeElement($image)) {
            // set the owning side to null (unless already changed)
            if ($image->getActualites() === $this) {
                $image->setActualites(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, CommentsActu>
     */
    public function getCommentsActus(): Collection
    {
        return $this->commentsActus;
    }

    public function addCommentsActu(CommentsActu $commentsActu): self
    {
        if (!$this->commentsActus->contains($commentsActu)) {
            $this->commentsActus[] = $commentsActu;
            $commentsActu->setActu($this);
        }

        return $this;
    }

    public function removeCommentsActu(CommentsActu $commentsActu): self
    {
        if ($this->commentsActus->removeElement($commentsActu)) {
            // set the owning side to null (unless already changed)
            if ($commentsActu->getActu() === $this) {
                $commentsActu->setActu(null);
            }
        }

        return $this;
    }

    public function _toString()
    {
        return $this->Title;
    }
}

src/Form/ActualitesType.php
<?php

namespace App\Form;

use App\Entity\Actualites;
use FOS\CKEditorBundle\Form\Type\CKEditorType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\HiddenType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ActualitesType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('Title')
            ->add('Description', CKEditorType::class)
            ->add('Date')
            ->add('parent', HiddenType::class)
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Actualites::class,
        ]);
    }
}

src/Controller/ActualitesController.php
<?php

namespace App\Controller;

use App\Repository\ActualitesRepository;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class ActualitesController extends AbstractController
{
    /**
     * @Route("/actualites", name="app_actualites")
     */

    public function index(
        ActualitesRepository $actualitesRepository,
        PaginatorInterface $paginator,
        Request $request
    ): Response {
        $data = $actualitesRepository->findAll();

        $actualites = $paginator->paginate(
            $data,
            $request->query->getInt('page', 1),
            9
        );

        return $this->render('actualites/index.html.twig', [
            'actualites' => $actualites,
        ]);
    }
}

templates/actualites/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Actualites{% endblock %}

{% block body %}
    <!-- =======================
Page Banner START -->
    <section class="bg-blue align-items-center d-flex" style="background:url(assets/images/pattern/04.png) no-repeat center center; background-size:cover;">
        <div class="container">
            <div class="row">
                <div class="col-12 text-center">
                    <!-- Title -->
                    <h1 class="text-white">Actualites</h1>
                    <!-- Breadcrumb -->
                    <div class="d-flex justify-content-center">
                        <nav aria-label="breadcrumb">
                            <ol class="breadcrumb breadcrumb-dark breadcrumb-dots mb-0">
                                <li class="breadcrumb-item"><a href="{{ path('app_main') }}">Accueil</a></li>
                                <li class="breadcrumb-item active" aria-current="page">Actualites</li>
                            </ol>
                        </nav>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- =======================
    Page Banner END -->
    <!-- =======================
    Page content START -->
    <section class="py-5">
        <div class="container">
            <div class="row">
                <!-- Main content START -->
                <div class="">

                    <!-- Course Grid START -->
                    <div class="row g-4">

                        {% for actualites in actualites %}
                            <!-- Card item START -->
                            <div class="col-sm-6 col-xl-4" >
                                <div class="card shadow h-100">
                                    <!-- Image -->
                                    <div class="card-body pb-0">
                                        <!-- Badge and favorite -->
                                        <div class="d-flex justify-content-between mb-2">
                                            <a class="badge bg-danger text-white">Actu</a>
                                        </div>
                                        <!-- Title -->
                                        <h5 class="card-title"><a href="{{ path('actualites_app_view_actualites',{'id':actualites.id}) }}">{{ actualites.title|u.truncate(50, '...', false) }}</a></h5>
                                        <p class="mb-2 text-truncate-2">{{ actualites.description }}</p>
                                    </div>
                                    <!-- Card footer -->
                                    <div class="card-footer pt-0 pb-3">
                                        <hr>
                                        <div class="d-flex justify-content-between">
                                            <span class="h6 fw-light mb-0"><i class="far fa-clock text-danger me-2"></i>{{ actualites.date|date('d-m-Y') }}</span>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <!-- Card item END -->
                        {% endfor %}
                    </div>
                    <!-- Course Grid END -->
                    <br>
                    <br>

                    <!-- Pagination START -->
                    <div class="col-12">
                        <nav class="mt-4 d-flex justify-content-center" aria-label="navigation">
                            {% do actualites.setPageRange(1) %}
                            {{ knp_pagination_render(actualites, 'main/pagination.html.twig') }}
                        </nav>
                    </div>
                    <!-- Pagination END -->

                </div>
            </div><!-- Row END -->
        </div>
    </section>
    <!-- =======================
    Page content END -->
{% endblock %}